### ISSUE TITLE
Shading selected day

### ISSUE THREAD

**Issue by jcaruso001** [SpongeBobSun/mCalendarView#13]
Is there a way to shade the selected day rather than mark it, like is done with the current day?

**Comment by SpongeBobSun** [comment]
Actually this is a simple fix but I think it's not proper to have a default clicking background.
Because people may have different highlight style in `OnDateClickListener`. So having a default clicking background may cause trouble.

So if you really want a clicking background, please implement it in `OnDateClickListener` and change the cell's background. You may also need a varaible to record last clicked cell so you can restore its normal background later. As i said, this is a simple fix.

**Comment by jcaruso001** [comment]
True, I can see why you don't want to do that, thanks for the work around.
